### ISSUE TITLE
Godwoken v0 mainnet:  "Cannot read property 'last_log' of undefined"

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-web3#187]
Request
```
curl 'https://mainnet.godwoken.io/rpc' \
 -H 'content-type: application/json' \
 --data-raw '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0xa2b619769edcaeb7feb19e214f2f6556ea61ca3f","from":"0x4b51bf8ed2c13d1104c0d22aa1c5c215d218b93b","value":"0x6fc23ac00","data":"0x"}],"id":1}'
```

Result:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32099,"message":"Cannot read property 'last_log' of undefined"}}
```

**Comment by Kuzirashi** [comment]
cc @RetricSu @classicalliu

**Comment by RetricSu** [comment]
hi, I noticed that the to address `0xa2b619769edcaeb7feb19e214f2f6556ea61ca3f ` in `eth_estimateGas` params is an `gw short address` of `eoa account`. however, currently in web3, we only support contract account address in such param. meaning that currently `eth_estimateGas` rpc only works for calling contract.

I also noticed that the eth transaction is about to transfer value from one eoa to another eoa account. in such case, we recommend using erc20 contract to transfer value in godwoken v0( however in v1 version, since we will remove [polyjuice-provider](https://github.com/nervosnetwork/polyjuice-provider/blob/main/docs/known-caveats.md) entirely, the compatibility will be more smooth), you can find [erc20 transfer example](https://github.com/classicalliu/gw-demos/blob/main/tests/transfer.test.ts) in [this repo](https://github.com/classicalliu/gw-demos).

**Comment by trulyliu** [comment]
@RetricSu Is the example you gave godwoken v0 or v1?

**Comment by RetricSu** [comment]
> @RetricSu Is the example you gave godwoken v0 or v1?

v0

**Comment by trulyliu** [comment]
Any v1 transaction example?

**Comment by RetricSu** [comment]
> Any v1 transaction example?

v1 is currently WIP, we don't have example yet. however, you can just deploy this [ERC20-proxy contract](https://github.com/nervosnetwork/godwoken-polyjuice/tree/compatibility-breaking-changes/solidity/erc20), and use this ERC20-proxy contract to transfer ckb. notice that the erc20-proxy contract require an `sudt_id` args in constructor, you need to fill it with ckb's sudt_id on godwoken, which is `1`.
