### ISSUE TITLE
Layer1 Deposit didn't create a account in Layer2

### ISSUE THREAD

**Issue by zmcNotafraid** [nervosnetwork/godwoken-web3#191]
https://explorer.nervos.org/aggron/transaction/0xd4e2f997a9c6c7b8ab05fb43ba835e70919833954e31870891ae72000991b8a4
output index: 0 , we parse the args and get a script_hash is : `0x28fc0c5c7b7710c27a44812ab4fb383f83a8552414de40b6c055bb74710c8395`
```

curl https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method":"gw_get_account_id_by_script_hash", "params": ["0x28fc0c5c7b7710c27a44812ab4fb383f83a8552414de40b6c055bb74710c8395"], "id": 1}'
{"jsonrpc":"2.0","id":1,"result":null}%          
```

**Comment by Flouse** [comment]
The `rollup_type_hash` in the args of https://explorer.nervos.org/aggron/address/ckt1qph5d47y28trukzwvrn2wjrx9hcyfe9d5vpfrcxnt2saphd3ydl5qqda8ak2d0wzw0ckn8n857mjetswpfe9qer0z6xs8tdt8zfttck0a7ssqqqqzqqqqqpsqqqqpxgqqqqraf4pnysnxxkg50m7c672aq80w35gf6evhalcep7lwgdxhjrewkrfqqqqqyqqqqqrqqqqqqcsqqqqdtyqylklmpj40g9s97utnh8fllptk2kqktcr2tm5jy4m23kuxaxqzdqqqqqt60mv567uyul3dx0x0fah9jhquznj2pjx795dqwk6kwyjkh3vlm73ve7t78xxpk55c88ke88myc08rdsy0aasqsqqqqqqqrqqynuamx
is outdated, since we have redeployed the Godwoken testnet_v1.

Please use `poly_getChainInfo` to get the latest chaininfo. 

```js
> curl https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -X POST -H "Content-Type: application/json" \
   -d '{"jsonrpc":"2.0","method":"poly_getChainInfo","params": [],"id":1}'

{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "rollupScriptHash": "0x9248c2ae34e8243ed30b311b0047a2691889f6d231b3991ee0ef5516c13547f4",
        "rollupConfigHash": null,
        "ethAccountLockTypeHash": "0x6ac8027edfd86557a0b02fb8b9dce9ffc2bb2ac0b2f0352f74912bb546dc374c",
        "polyjuiceContractTypeHash": "0x848753a2b16c63682c7de4e6cc7167890ff3f821d61328f45386d91ece54373e",
        "polyjuiceCreatorId": "4",
        "chainId": "868450977185796"
    }
}
```
