### ISSUE TITLE
All polyjuice contract have created_contract_address_hash receipt?

### ISSUE THREAD

**Issue by zmcNotafraid** [nervosnetwork/godwoken-web3#306]
First, we can use `eth_getTransactionReceipt `RPC to  get a deploy contract tx's generated contract address, as: created_contract_address_hash.
But after I compare with all created_contract_address_hash and all account in my database. I found created_contract_address_hashes are less than polyjuice contract account.
So an polyjuice contract account can be generated without these created_contract_address_hash way or something I missed?

**Comment by magicalne** [comment]
> But after I compare with all created_contract_address_hash and all account in my database. I found created_contract_address_hashes are less than polyjuice contract account.

I'm not sure how you get **polyjuice contract accounts** in your code. Paste code snippet could be helpful. :thinking:

**Comment by zmcNotafraid** [comment]
> > But after I compare with all created_contract_address_hash and all account in my database. I found created_contract_address_hashes are less than polyjuice contract account.
> 
> I'm not sure how you get **polyjuice contract accounts** in your code. Paste code snippet could be helpful. 🤔

I get the account count by global state. Then I compare with my database account tables  ids.Because the id is sequence.So I can create all godwoken account to my database.At last I can filter all polyjuice contract

**Comment by magicalne** [comment]
Let me try to rephrase your question.
You set up a local devnet with kicker. And deploy contracts with maybe ethers or web3 API. Every time a new contract account is created successfully, you insert this account id into your database. Finally, it turns out the number of contract accounts created by yourself is less than total account number in godwoken.

Is that correct?
Well, some account ids are reserved in godwoken. Like [meta-contract](https://github.com/nervosnetwork/godwoken/blob/develop/docs/life_of_a_godwoken_transaction.md#metacontract), meta contract is the first account in godwoken, this contract can be used to create accounts in a "godwoken" way. So do the other internal contracts. You can see there are already several accounts in godwoken when the kicker is just set up.

And when you deposit from L1 to L2 at the first time, godwoken will create a new EOA account. I guess you store this account to your DB too. If you don't use `create` or `create2` in your contract, there is no place to create more accounts.

**Comment by zmcNotafraid** [comment]
I'm the develop of https://github.com/Magickbase/godwoken_explorer.

And when sync all godwoken V0 mainnet block data.First, I filter all created_contract_address_hash from polyjuice transaction's receipt.Then I filter all polyjuice_contract account. I compare with two data.I found some polyjuice_contract account 's address can't found in created_contract_address_hash .
So I have two guess:
1. When I sync I lost some created_contract_address_hash from receipt
2. Some polyjuice contract account have some special situation, it will not appear in reciept.

If I knonw a polyjuice_contract address, can I get which tx creeated it?

**Comment by zmcNotafraid** [comment]
such as this issue: https://github.com/Magickbase/godwoken_explorer/issues/456
The deployment tx hash is 0x03e6156e17ffe986a02cea4ae454a41c3e5418dec780acc08fce20ed4c299e24, but  we get from it's receipt have none contract address.So how can I know 0x03e6156e17ffe986a02cea4ae454a41c3e5418dec780acc08fce20ed4c299e24 tx will generate 0x8967aF2789aabbc6Ff68BD75336b09e6E4303C98 contract.

```
curl  https://mainnet.godwoken.io/rpc  -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method":"eth_getTransactionReceipt", "params": ["0x03e6156e17ffe986a02cea4ae454a41c3e5418dec780acc08fce20ed4c299e24"], "id": 1}'
```

**Comment by magicalne** [comment]
I don't know about this tx in detail. But I'm pretty sure this is not a contract creation tx. Or in another way, this tx is not just about creating a contract.

You may find out there is a log item of this receipt containing the contract address that you mentioned. See the data field.
```json
{
        "address": "0x5ef0d2d41a5f3d5a083bc776f94282667c27b794",
        "blockHash": "0xf485d5db90ac2a55ad2a345b16c591b644c50fcc150cd66735bdeb7ae25e55c3",
        "blockNumber": "0x9fbc",
        "transactionIndex": "0x16",
        "transactionHash": "0x03e6156e17ffe986a02cea4ae454a41c3e5418dec780acc08fce20ed4c299e24",
        "data": "0x0000000000000000000000008967af2789aabbc6ff68bd75336b09e6e4303c980000000000000000000000000000000000000000000000000000000000000001",
        "logIndex": "0x0",
        "topics": [
          "0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9",
          "0x000000000000000000000000b02c930c2825a960a50ba4ab005e8264498b64a0",
          "0x000000000000000000000000e934f463d026d97f6ce0a10215d0ac4224f0a930"
        ],
        "removed": false
},
```

Hope It helps.

**Comment by zmcNotafraid** [comment]
Thanks! I got it.
